### ISSUE TITLE
[Improvement Suggestion] Device Handling - Reduce CPU-GPU Overhead

### ISSUE THREAD

**Issue by ImahnShekhzadeh** [atong01/conditional-flow-matching#102]
Hi! 

I noticed that in several places of the code, e.g. in the [`conditional_mnist.ipynb`](https://github.com/atong01/conditional-flow-matching/blob/main/examples/images/conditional_mnist.ipynb) tutorial, there's a slight CPU-GPU overhead. For example, the line
```
torch.randn(100, 1, 28, 28).to(device)
```
first creates the tensor on the CPU and then copies it onto the GPU (in case `device` is `cuda:0`).

It is possible to directly create the tensor on the specified device via
```
torch.randn(100, 1, 28, 28, device=device)
```
which is more memory-efficient, since there's no CPU-GPU overhead.

**Comment by kilianFatras** [comment]
Hello,

You are right. It would be indeed more efficient to create tensors this way. I do not mind the current implementation as the purpose of tutorials is to show how we can train flow matching methods. I will check for cifar10 training but that will have to wait a bit.

**Comment by ImahnShekhzadeh** [comment]
`train_cifar10.py` is indirectly affected by this, since `utils_cifar.py` has some CPU-GPU overhead, e.g. in [L37](https://github.com/atong01/conditional-flow-matching/blob/main/examples/images/cifar10/utils_cifar.py#L37) in the `generate_samples()` function. Some other Python scripts are affected by this as well.

I am actually currently working on fixing this, I can open a draft PR once I am finished.

**Comment by atong01** [comment]
That's great, yep a simple improvement. I was never too worried about this, as I was pretty sure that it didn't matter with most of the time in the Unet. Would be very curious if you notice a speedup! Regardless slightly better and welcome the PR.

**Comment by ImahnShekhzadeh** [comment]
I performed some tests by running `train_cifar10.py` with the same flags specified in the README (except the number of training steps and the number of steps at which samples are generated, which I reduced to `1000` and `500` respectively), I did not notice a speedup (some minor fluctuations only). What surprises me is that the memory consumption, which I logged via `torch.cuda.max_memory_allocated()`, remained the same :thinking:

Will open a PR shortly.
