### ISSUE TITLE
Remove Pytorch Lightning?

### ISSUE THREAD

**Issue by GeoffStr** [atong01/conditional-flow-matching#121]
Hi!

Great repo.

The only difficulty I have is that the pytorch lightning abstractions have made integrating into other projects pretty hard. I tend to think plain pytorch is actually cleaner and easier to understand these days -- as well as much more flexible :)! I would love to build on your work, but I'm a bit stuck with the pytorch lightning induced issues. 

Do you have any plans on the roadmap to pull out the pytorch lightning related code? If so, I would be really interested in helping! Thanks!

**Comment by atong01** [comment]
Closing for now. If anyone feels like helping on this please feel free to reopen!
