### ISSUE TITLE
Problem training 8 gaussians to moons with TargetConditionalFlowMatcher

### ISSUE THREAD

**Issue by fatpmeireles** [atong01/conditional-flow-matching#126]
Dear all,

I'm getting started with Flow Matching and working through your tutorial notebooks. I've tried implementing the `TargetConditionalFlowMatcher` from the OT-CVF Lipman et al. formulation but the model is not training properly. I've tried going through the code but still can't figure out what I am doing wrong, could you please help solve this? Here is the code with an early trajectory output:

```
%%time
sigma = 0.1
dim = 2
batch_size = 256
model = MLP(dim=dim, time_varying=True)
optimizer = torch.optim.Adam(model.parameters())
FM = TargetConditionalFlowMatcher(sigma=sigma) # From Lipman et al 2023

start = time.time()
for k in range(20000):
    optimizer.zero_grad()

    x0 = sample_8gaussians(batch_size)
    x1 = sample_moons(batch_size)

    t, xt, ut = FM.sample_location_and_conditional_flow(x0, x1)
    ut = FM.compute_conditional_flow(x0, x1, t, xt) # Recomputing ut

    vt = model(torch.cat([x1, t[:, None]], dim=-1))
    loss = torch.mean((vt - ut) ** 2)


    loss.backward()
    optimizer.step()

    if (k + 1) % 5000 == 0:
        end = time.time()
        print(f"{k+1}: loss {loss.item():0.3f} time {(end - start):0.2f}")
        start = end
        node = NeuralODE(
            torch_wrapper(model), solver="dopri5", sensitivity="adjoint", atol=1e-4, rtol=1e-4
        )
        with torch.no_grad():
            traj = node.trajectory(
                sample_8gaussians(1024),
                t_span=torch.linspace(0, 1, 100),
            )
            plot_trajectories(traj.cpu().numpy())
torch.save(model, f"{savedir}/tcfm_v1.pt")
```
![image](https://github.com/user-attachments/assets/177ba587-214e-4a63-9981-a3634280aa63)

Thank you in advance for your help and this amazing resource!

**Comment by atong01** [comment]
Hi!

The target conditional flow matcher from Lipman only works when the prior is N(0,1) as we have implemented here. Since your prior is 8 Gaussians the math does not work here. Hope this helps!

--Alex

**Comment by fatpmeireles** [comment]
Ah yes, that's true, I completely missed this point. Thank you very much for your help! I'll close this issue now.

Cheers,
Fernando

**Comment by fatpmeireles** [comment]
Just for completeness, if  I do start from the correct prior the flow matcher works:
![image](https://github.com/user-attachments/assets/75c7fae0-d098-4dd9-9aa9-86ca81b29d73)
