### ISSUE TITLE
omegaconf.errors.InterpolationKeyError: Interpolation key 'local.log_dir' not found

### ISSUE THREAD

**Issue by DISHENGRZH** [atong01/conditional-flow-matching#130]
Hello, Thanks for your great work!
However, when I run the eval, I meet the error as the title. It seems to be a problem related to the config file. How can I solve the problem？
I have revised the path to run the code. 
`python eval.py ckpt_path="/path/to/ckpt/name.ckpt"`
Meet the fault as below.
 ```
   raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'local.log_dir' not found
    full_key: hydra.run.dir
    object_type=dict
```

**Comment by atong01** [comment]
Hi, if you look in the config you will see that hydra.run.dir is looking for a `local.log_dir` path. You can either set this or set `hydra.run.dir` to something else.

**Comment by DISHENGRZH** [comment]
Thank you.
