### ISSUE TITLE
zero_module in UNet output

### ISSUE THREAD

**Issue by chihchiehchen** [atong01/conditional-flow-matching#134]
Hello, 

Thanks for sharing your great work. I have a question on the self.out layer of UNet module. 
I found the last layer is zero_module(conv_nd(dims, input_ch, out_channels, 3, padding=1)), does it mean all the network outputs will be zero since the weights and biases of last layer of UNet are all zeros?

I know that must not be true but I do not know how to justify it. Could you give me some hints? In any case thanks for your patient and help!

**Comment by atong01** [comment]
Hi, yes, this means that the network outputs will all be zero **at initialization**. After training, the network weights will no longer be all zeros.

**Comment by chihchiehchen** [comment]
I see, thanks for your help!
