### ISSUE TITLE
SF2M tutorial: Implementation Regarding OTPlanSampler Regularization

### ISSUE THREAD

**Issue by CaioDaumann** [atong01/conditional-flow-matching#143]
Hi, 

On appendix A.1 in the SF2M paper, the following is written:

> Notably, the minibatch OT plan is closer to the entropic OT plan than the minibatch entropic OT plan. That is why in our experiments, we observed that the minibatch approximation with exact optimal transport outperforms the minibatch approximation with the entropic OT cost.

But if I open the SF2M tutorial, The `FM = SchrodingerBridgeConditionalFlowMatcher(sigma=sigma)` is used, and if I look into class, the `OTPlanSampler` is regularised: `OTPlanSampler(method=ot_method, reg=2 * self.sigma**2)`

Question:

Could you please explain why the OTPlanSampler is regularized in the tutorial despite the paper mentioning the use of exact optimal transport without regularization? Is there an underlying reason for this discrepancy, or am I misunderstanding the implementation details?

Thanks for the awesome package and for your assistance!

Best,
Caio

**Comment by atong01** [comment]
Hi!

Yes we found often the exact transport plan works quite well as it is a different form of regularization. The default in the tutorial is with regularization for demonstration purposes. Depending on your application I would start with exact. It's faster for most common batch sizes, and as we show often just as good empirically.

--Alex

**Comment by CaioDaumann** [comment]
I see! Thanks for the answer! Closing the issue now ...
