### ISSUE TITLE
code for RectifiedFlow

### ISSUE THREAD

**Issue by arakotom** [atong01/conditional-flow-matching#150]
Hello,

Thank you very much for this nice package. 
I wanted to kindly ask if, as stated in the implemented papers section,  the code for  RectifiedFlow (Liu et al 2023) is provided?

Alain

**Comment by kilianFatras** [comment]
Hi @arakotom,

To get 1-Rectified Flow, you just need to use the I-CFM method with \sigma=0.0.  If you want to use k-rectified flow, you will need to retrain k times the models between noisy samples and their generated samples counterparts.

**Comment by arakotom** [comment]
Hi @kilianFatras ,

thanks for the answer. so in a nutshell, for the k-rectified flow, I need to recode myself all the boilerplates/loops about generating samples and retraining again with I-CFM.

**Comment by atong01** [comment]
Hi @arakotom,

Correct, we don't have a simple example for this. Would be great to add one. To check out how I ran it for the paper you can look here: 

https://github.com/atong01/conditional-flow-matching/blob/62c44affd877a01b7838d408b5dc4cbcbf83e3ad/runner/src/models/cfm_module.py#L539

**Comment by kilianFatras** [comment]
Closing as solved
