### ISSUE TITLE
the usage of ema

### ISSUE THREAD

**Issue by cb6e310** [atong01/conditional-flow-matching#152]
hi, great work! i just would like to ask what is the role of ema in cifar10 example?

**Comment by atong01** [comment]
ema improves the performance by quite a bit on cifar (2-3 FID if I remember correctly). Would say this is fairly standard in diffusion models due to large variance in the gradients.

**Comment by kilianFatras** [comment]
Hi. Alex is right. Furthermore, without EMA, the FID is around 7.5. With EMA, the FID is around 3.7.
