### ISSUE TITLE
Reproducing CelebA Image-to-Image translation

### ISSUE THREAD

**Issue by benearnthof** [atong01/conditional-flow-matching#29]
Hi, thanks for this very interesting codebase! 
I'd like to reproduce the CelebA Image-to-Image example presented at the end of:  
[https://arxiv.org/pdf/2302.00482.pdf](https://arxiv.org/pdf/2302.00482.pdf)  
Are you planning to add example code for this or could you point me in the right direction? 

Best regards!

**Comment by atong01** [comment]
Hi @benearnthof 

We will look into releasing this code. Will update shortly. It should be fairly easy to adapt the mnist notebook code, replacing the starting Gaussian with samples from celeb a

**Comment by benearnthof** [comment]
Hello @atong01 thank you for your quick reply! I will try this today thank you very much, looking forward to updates to this repository!

**Comment by kilianFatras** [comment]
This can be done by adapting the recently added feature https://github.com/atong01/conditional-flow-matching/tree/main/examples/cifar10.

I am closing the issue. Feel free to reopen in case of extra questions.
