### ISSUE TITLE
Tests failing due to sklearn dependency

### ISSUE THREAD

**Issue by atong01** [atong01/conditional-flow-matching#3]
Waiting on https://github.com/DiffEqML/torchdyn/issues/180

**Comment by yuanzhi-zhu** [comment]
Hi @atong01 , I've encountered the dependency error that `The 'sklearn' PyPI package is deprecated, use 'scikit-learn'` when use `pip install torchdyn==1.0.3`.
And as it's said in the readme file, version 1.0.4 is broken.
Could you help check this?

**Comment by atong01** [comment]
Hi @yuanzhi-zhu, I actually just fixed torchdyn and pushed version 1.0.5 https://github.com/DiffEqML/torchdyn/releases/tag/1.0.5.1 you should be able to pip install torchdyn again.
