### ISSUE TITLE
Road to 1.1

### ISSUE THREAD

**Issue by kilianFatras** [atong01/conditional-flow-matching#37]
I am opening this issue to discuss the road we should follow to the 1.1 version. Here is the list of the changes I would like to see:

- [ ] (WIP) Add Cifar10 experiments 
- [ ] Use torchdiffeq and remove torchdyn in examples
- [ ] Upgrade to Torch 2.0 (and update requirements)
- [ ] Add Tests 
- [ ] Add conditional examples

**Comment by josephdviviano** [comment]
I totally agree. I'd suggest the following:

1) Upgrade to torch 2 first.
2) Handle the tests next.
3) Add the conditional examples.

If you do this in 3 sequential PRs they will be less nasty and confusing.

The change from `torchdiffeq` is because the `torchdyn` folks refuse to maintain their code?

Makes sense. But I think I would do this change in parallel with the move to pytorch 2, because you might discover nasty bugs upgrading to pytorch 2 and realizing those packages don't play nice with it.

**Comment by atong01** [comment]
I believe the basic torchcfm codebase plays fairly nicely with torch 2.0, but the code in `runner` reproducing things from the papers does not. Specifically even the versions of `pytorch_lightning` and even `torch_metrics` seem to break existing tests in the `runner` code. I think we should probably keep the fully reproducible paper code requiring `torch < 2.0`, but make nicer code in torch 2.0.

**Comment by kilianFatras** [comment]
Ok. I agree with the two of you. @atong01, I was thinking about it. What about the specific requirement.txt within runner?

**Comment by josephdviviano** [comment]
you could indeed have two different pip installs. You could at that point also consider making runner a separate repo that imports from this library if it's main purpose is archival (one could imagine pulling over a few examples that are torch2 compatible into the main library as a set of explanatory examples).

**Comment by kilianFatras** [comment]
@josephdviviano @atong01 I think the priority is to make a clean cifar10 folder. I am already working on it and hope to submit PR by the end of the week.
https://github.com/kilianFatras/conditional-flow-matching/tree/cifar10_experiments

**Comment by kilianFatras** [comment]
@atong01 @josephdviviano I have been thinking about the current structure of the library. I would like to change some elements and request your opinions. 
- The current folder 'models' within the torchcfm folder should either be moved to the main folder or within examples. It does not make a lot sense to have where it is now.
- The current file 'utils' within the torchcfm folder should either be moved to the main folder. It does not make a lot of sense to have where it is now. In addition, it should become a folder as we will have a lot of new utils elements not related to Euclidean space in the coming months. We could also put everything related to drawing toy datasets and SDE/ODE elements in different files.

**Comment by josephdviviano** [comment]
+ I agree `torchcfm.models` should become `examples.models`.
+ If the `utils` files are useful for handling different spaces maybe they should stay in the main library?
+ You could have a module `utils` with submodules `spaces`, `plotting`, sde`, ... if you think it saves your users time.

**Comment by samedii** [comment]
I noticed that torchdyn has released v1.0.6 in case that changes anything for you

Also, thanks for the very nice and easy to read code! :D

**Comment by kilianFatras** [comment]
Hi @samedii, thank you for your interest in our TorchCFM library! Yes, we are aware of torchdyn 1.0.6 and that it solves some of our issues :). 

 @atong01 @josephdviviano let's discuss which tests should be added to the library. With torchdyn 1.0.6 everything is working now (note that I will recompute all examples next week with torch2.0 to be 100% sure). Also, the conditional_examples are ready (pep8 to finalize before merging).

**Comment by josephdviviano** [comment]
Just FYI this week for me is a bit crazy, let's book a slot next week to
discuss :)
Joseph Viviano
@josephdviviano <https://twitter.com/josephdviviano>
viviano.ca

**Comment by kilianFatras** [comment]
Note about the 1.0.4 release (7-10 days):

1. Release better Cifar 10 code (large and small models for FID 5-6)
2. Release Intro to Flow Matching notebook
3. Release Single cell notebook with conditional generation from a given sample (SB-CFM vs SF2M)

@atong01 anything else to add?

**Comment by josephdviviano** [comment]
Happy to have a discussion -- also happy to do any code reviews or issues, just tag me :)

**Comment by kilianFatras** [comment]
The PR on Forest-Flow is ready to be merged and it is waiting for approval from @atong01. It also adds a test on the time vector 't'.

I have opened a PR on tests. Note that this is a first draft that ensures that the main classes are working. I will add in the future tests on the OT classes as well.
