### ISSUE TITLE
Question regarding the noise std in eq(14)

### ISSUE THREAD

**Issue by yuanzhi-zhu** [atong01/conditional-flow-matching#47]
1. Is it true that for OT CFM, we choose $\sigma=0$ when $x_0 \sim N(0,1)$?
2. How should we choose $\sigma$ when both  $p_0$ and $p_1$ are non-Gaussian dist.?

Massive thanks in advance!!

**Comment by atong01** [comment]
Hi @yuanzhi-zhu I think $\sigma=0$ is a good default choice in both the Gaussian and the non-Gaussian source cases. Sometimes a larger $\sigma$ helps to generalize a bit better, but this is not a huge effect we think.
