### ISSUE TITLE
Any tips for noisy final steps

### ISSUE THREAD

**Issue by samedii** [atong01/conditional-flow-matching#54]
Hi again! Been playing around with finetuning SD using your codebase. It's worked pretty well and seems to converge quickly compared to eps/v-objective. However, I'm seeing noise appear in the final steps (around t = 0.6 to t=1.0) during sampling. (It is looking clean before then). This is pretty surprising because it should be obvious to the model that there shouldn't be any noise there

Here's an example:
![image](https://github.com/atong01/conditional-flow-matching/assets/1872050/b35ea590-f58e-4018-99b6-2ea1fa3f0e77)

It doesn't happen every time but maybe 20% of the time.

I've tried training with sigma=0.0 and sigma=0.1. The std of my data is around 0.5.

Any thoughts or tips?

**Only maybe related:**
I noticed that this simple implementation:
https://gist.github.com/francois-rozet/fd6a820e052157f8ac6e2aa39e16c1aa

Uses this setup instead
```
y = (1 - t) * x + (1e-4 + (1 - 1e-4) * t) * z
u = (1 - 1e-4) * z - x
```

And I thought this might be related. I know that the "eps" objective and "predicting denoised image" objective work badly at different ends of the timesteps

**Comment by kilianFatras** [comment]
Can you provide a simple example to reproduce your problem? I am not sure to follow what is going on here.

**Comment by samedii** [comment]
Sorry this seems to resolve eventually after training for long enough. I'll close this :)
