### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by President-T** [atong01/conditional-flow-matching#70]
python3 compute_fid.py --model "otcfm" --step 400000 --integration_method dopri5;
bug:
XXX/python3.10/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by atong01** [comment]
Thanks for the issue! I haven't seen this before. Could you give a bit more context on the error? ideally the full trace, but ideally what in our code leads to this.

**Comment by President-T** [comment]
I'm very sorry, the above bug is due to an issue with my Python environment and has been resolved. Thank you for your reply！

**Comment by atong01** [comment]
No problem at all! Perhaps someone else will have the same issue in the future and this will help them. Closing the issue.
