### ISSUE TITLE
Parallel problem

### ISSUE THREAD

**Issue by zhuqunxi** [atong01/conditional-flow-matching#82]
Thank you for your GREAT work. However,  when I set ‘--parallel True’ in the CIFAR10 experiment, the code cannot run.  How to fix it. Thanks.

![image](https://github.com/atong01/conditional-flow-matching/assets/22273557/1f69208e-0df7-4e4a-a983-423c0027565b)

**Comment by kilianFatras** [comment]
Thanks for your interest. We are aware of this problem. It is due to Torchdyn that cannot handle the parallel setting, unfortunately... I think Torchdyn tries to generate samples over a single GPU and this is what causes the bugs.

For now, I would simply comment the generate_samples lines during training. Note that this is supposed to work fine for inference as we convert the model trained on several GPUs on a single GPU to do inference.

@atong01 I think we should add a comment explaining this behaviour. Also, the "parallel" FLAG is not used within compute_fid.py

**Comment by kilianFatras** [comment]
I have implemented a fix here: https://github.com/atong01/conditional-flow-matching/tree/fix_bugs. I think it works fine. I am running some tests. Feel free to try and reproduce it as well :)

**Comment by zhuqunxi** [comment]
> I have implemented a fix here: https://github.com/atong01/conditional-flow-matching/tree/fix_bugs. I think it works fine. I am running some tests. Feel free to try and reproduce it as well :)

Thank you very much for your help. It looks good now. I'll try it.

**Comment by kilianFatras** [comment]
After two tests, the above fix does not seem to perform as well as the previous method. I got an FID of 4.9 for the two tests while it should be 3.6. Therefore, I would suggest training on a single GPU with the main branch. It only takes 7Gb. Fixing the parallel training might take me some time.

**Comment by kilianFatras** [comment]
Note that if you want to train in parallel with the main branch, you can just comment the generate_samples lines. It will work just fine and save the weights.

**Comment by zhuqunxi** [comment]
> Note that if you want to train in parallel with the main branch, you can just comment the generate_samples lines. It will work just fine and save the weights.

Does 'It will work just fine' mean that we can get a good FID via training in parallel with the main branch?

**Comment by kilianFatras** [comment]
Yes, I think so. I would be extremely surprised if it does not. FID should be between 3.6 and 4.

**Comment by zhuqunxi** [comment]
> Yes, I think so. I would be extremely surprised if it does not. FID should be between 3.6 and 4.

Thanks. But I still have no idea what caused this FID problem.

**Comment by zhuqunxi** [comment]
> Yes, I think so. I would be extremely surprised if it does not. FID should be between 3.6 and 4.

I got an FID of 5.08 using the original downloaded code.

**Comment by kilianFatras** [comment]
With or without parallel? Without parallel, I have been able to reproduce an FID below 4 several times as well as other users. So such a high FID does not seem good to me. The shared trained weights should also give an FID below 4. 

Something is not working with parallel. I do not what exactly and I will try one or two other fixes. However, I will not have time to investigate this issue further for some time. I recommend for now to use the main branch and not use parallel.

**Comment by kilianFatras** [comment]
I have tested the main branch and got an FID of 3.8. I will try to check if the problem is not in the inference script with parallel (the way the weights are loaded). For all users, please use the main branch without parallel. The requested memory is about 7Gb on your GPU and therefore it is easy to train on a single GPU.

**Comment by kilianFatras** [comment]
The best FID I have gotten with parallel is 4.6. 

Dataparallel computes some statistics on their own device (like batch nor for instance). As I use 2 GPUs, I doubled the batch size (i.e., 256) for the statistics to be computed on batch of 128 to match what is done on 1 GPU. It still does not work as good as a single GPU (FID of 3.8 vs 4.6) but it gets closer. I do not know what to do to get the same FID. We might implement distributed data parallel in the future but not before ICML deadline.

**Comment by kilianFatras** [comment]
Hello,

I am sure that the code is correct and that the lower FID is due to dataParallel. Feel free to use it :) Just be aware that it results in a slightly lower FID than training over 1 GPU.

Best,
Kilian
