### ISSUE TITLE
Variance reduction over minibatches?

### ISSUE THREAD

**Issue by ameya98** [atong01/conditional-flow-matching#91]
Hi, thanks for this great implementation!
I was wondering where the variance reduction method described in [Appendix C.1](https://arxiv.org/abs/2302.00482) is present in this code. Also, is there an easy way to reproduce the results of Appendix D.1 on variance reduction?

**Comment by atong01** [comment]
Hi @ameya98,

The code I used is here: https://github.com/atong01/conditional-flow-matching/blob/6b3adb46750df045e9285f0b2833382ed87cec7a/runner/src/models/cfm_module.py#L203-L216

I believe something like this command will get you close to the results in D.1
```
#!/bin/bash
python src/train.py -m experiment=cfm \
  model=sbcfm,cfm,fm \
  +model.avg_size=1,2,4,8,16,32,64,128,256,512 \
  datamodule=twodim \
  datamodule.batch_size=512 \
  trainer.check_val_every_n_epoch=1 \
  trainer.max_epochs=1000 \
  seed=42,43,44,45,46 &
```

**Comment by kilianFatras** [comment]
@ameya98 did it work for you?
