### ISSUE TITLE
Question about `UNetModel` used in `conditional_mnist.ipynb`

### ISSUE THREAD

**Issue by ImahnShekhzadeh** [atong01/conditional-flow-matching#96]
Hi, 

First of all thanks for this amazing repository!

In [`conditional_mnist.ipynb`](https://github.com/atong01/conditional-flow-matching/blob/main/examples/images/conditional_mnist.ipynb), the `UNetModel` is called like this,
```
model = UNetModel(
    dim=(1, 28, 28), num_channels=32, num_res_blocks=1, num_classes=10, class_cond=True
).to(device)
```
The above code works fine, but I do not fully understand why, since the `UNetModel` itself does not have these arguments, but instead the wrapper `UNetModelWrapper`

**Comment by kilianFatras** [comment]
Thank you for your interest. 

The UNet model has the input argument "num_classes" set by default to None (https://github.com/atong01/conditional-flow-matching/blob/main/torchcfm/models/unet/unet.py#L410). When num_classes is not none, it is used to create a label embedding (see https://github.com/atong01/conditional-flow-matching/blob/main/torchcfm/models/unet/unet.py#L448).

To call it when we want to use conditional generation, we use the wrapper with two parameters (class_cond and num_classes) (see https://github.com/atong01/conditional-flow-matching/blob/main/torchcfm/models/unet/unet.py#L913).

I hope this helps.

**Comment by ImahnShekhzadeh** [comment]
Thanks a lot, this is very helpful!
